name: device_frame
description: Mockups for common devices.
version: 1.1.0
homepage: https://github.com/aloisdeniel/flutter_device_preview/device_frame

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  flutter_lints: ^2.0.3
  xml: ^6.3.0
  recase: ^4.1.0
